#dev version, which include pecl and xdebug
FROM php:8.0.3-fpm

RUN apt-get update && apt-get install -y \
git \
zip \
unzip

# if need composer to update plugin / vendor used
RUN php -r "copy('http://getcomposer.org/installer', 'composer-setup.php');" && \
php composer-setup.php --install-dir=/usr/bin --filename=composer && \
php -r "unlink('composer-setup.php');"

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.start_with_request=trigger" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.discover_client_host=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_port=9003" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \ 
    && echo "xdebug.idekey=VSCODE" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    # enable trigger xdebug
    && echo "xdebug.var_display_max_depth=10" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.log=/var/log/xdebug.log" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    # set xdebug.trigger_value
    && echo "xdebug.trigger_value=1234" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    # xdebug.connect_timeout_ms=1000
    && echo "xdebug.connect_timeout_ms=10000" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    # xdebug.remote_handler=dbgp
    && echo "xdebug.remote_handler=dbgp" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.var_display_max_children=250" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    # xdebug.var_display_max_data=10000
    && echo "xdebug.var_display_max_data=10000" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini



# copy all of the file in folder to /src
COPY ./backend /tmp/app
WORKDIR /tmp/app
RUN composer update

RUN mv vendor / && rm -rf /tmp/app
WORKDIR /app
# run the php server service
# move this command to -> docker-compose.yml
# CMD php -S 0.0.0.0:8080 public/index.php

# RUN composer create-project --prefer-dist laravel/lumen /tmp/lumen && mv /tmp/lumen/vendor / && rm -rf /tmp/lumen

