version: '3.1'

services:
# How to make init only run once?
  init:
    build:
      context: ..
      dockerfile: ./Architecture/init/Dockerfile
    command: /init.sh 
    volumes:
      - ./init/init.sh:/init.sh
      - ../backend:/app/backend
      - ../frontend:/app/frontend
