version: '3.1'

services:

  # init:
  #   build:
  #     context: ..
  #     dockerfile: ./Architecture/init/Dockerfile
  #   command: /init.sh 
  #   volumes:
  #     - ./init/init.sh:/init.sh
  #     - ../backend:/app/backend
  #     - ../frontend:/app/frontend
  # this move out as seperated docker-compose-init.yml, works good
  
  frontend:
    build:
      context: ..
      dockerfile: ./Architecture/react/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ..
      dockerfile: ./Architecture/lumen/Dockerfile-dev
    ports:
      - "8080:8080"
    command: php -S 0.0.0.0:8080 public/index.php
    volumes:
      - ../backend:/app
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mydatabase
      DB_USERNAME: user
      DB_PASSWORD: password

  db:
    image: mysql:5.7
    ports:
      - "3366:3306"
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - db


volumes:
  dbdata:
