<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;



class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {

        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('first_name')->nullable(); // Maps to "firstName"
            $table->string('last_name')->nullable(); // Maps to "lastName", nullable because it's disabled in the form and might not be submitted
            $table->string('email')->unique(); // Maps to "email", unique because it's the username
            $table->integer('age')->nullable(); // Maps to "age", integer type for age
            $table->text('bio')->nullable(); // Maps to "bio", text type for longer input
            $table->string('password'); // Maps to "password"
            $table->string('language')->nullable(); // Maps to "language", nullable because it's a select and might not be required
            $table->string('role')->default('user'); // Maps to "role", default value is "user"
            $table->string('api_token', 60)->unique()->nullable(); // Maps to "apiToken", unique because it's the token, nullable because it's generated by the server
            $table->timestamps(); // Adds created_at and updated_at columns
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
